[project]
name = "route-planning"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
