"""Abstract geometry classes for core geometry objects."""
import json
from abc import ABC, abstractmethod


class ABCGeo(ABC):
    """
    Abstract class for core geometry objects.
    """

    @abstractmethod
    def save(self) -> str:
        """
        Return JSON string representation of the object.
        """

    @classmethod
    def load(cls, json_data: str) -> "ABCGeo":
        """
        Create object from JSON string.

        Args:
            json_data: JSON string generated by save() method

        Returns:
            New instance of the class.

        """
        return cls(*json.loads(json_data))
