"""Point geometry class for core."""
import json

from .abstract_geometry import ABCGeo
from .basic_validation_functions import BasicValidationFunctions


class Point(ABCGeo):
    """
    Point core class.
    """

    X_MAX_COORDS: float =  1000.0
    X_MIN_COORDS: float = -1000.0
    Y_MAX_COORDS: float =  1000.0
    Y_MIN_COORDS: float = -1000.0

    def __init__(self, x: float = 0, y: float = 0) -> None:
        """
        Initialize 2D point.

        Args:
            x: X-coordinate of the point
            y: Y-coordinate of the point

        Raises:
            ValueError if coordinates do not fit in certain range

        """
        BasicValidationFunctions.check_coord(x, "x")
        BasicValidationFunctions.check_coord(y, "y")
        self._x = x
        self._y = y

    def save(self) -> str:
        """
        Return JSON string representation of the object.
        """
        return json.dumps((self._x, self._y))

    @classmethod
    def load(cls, data: str) -> "Point":
        """
        Create object from JSON string.

        Args:
            data: JSON string generated by save() method

        Returns:
            New instance of the class.

        """
        return cls(*json.loads(data))

    @property
    def x(self) -> float:
        """
        Return x coordinate of point.
        """
        return self._x

    @x.setter
    def x(self, x_coord: float) -> None:
        """
        Set x coordinate of point.

        Args:
            x_coord: new x-coordinate of the point

        Raises:
            ValueError if x coordinate does not fit in certain range

        """
        BasicValidationFunctions.check_coord(x_coord, "x")
        self._x = x_coord

    @property
    def y(self) -> float:
        """
        Returns y coordinate of point.
        """
        return self._y

    @y.setter
    def y(self, y_coord: float) -> None:
        """
        Set y coordinate of point.

        Args:
            y_coord: new y-coordinate of the point

        Raises:
            ValueError if y coordinate does not fit in certain range

        """
        BasicValidationFunctions.check_coord(y_coord, "y")
        self._y = y_coord

    def __str__(self) -> str:
        """
        Return string representation of point.
        """
        return f"({self._x}, {self._y})"

    def __eq__(self, other: "Point") -> bool:
        """
        Compare two points.
        """
        return self.x == other.x and self.y == other.y

    def __hash__(self) -> int:
        """
        Return hash of point.
        """
        return hash((self.x, self.y))

    def distance_to(self, point: "Point") -> float:
        """
        Calculate distance between two points.
        """
        return ((self.x - point.x) ** 2 + (self.y - point.y) ** 2) ** 0.5

    @staticmethod
    def check_point_instance(*args: object) -> None:
        """
        Compare object type to Point type.

        Args:
            args: set of objects which type want to be checked

        Raises:
            TypeError if type of any object is not Point.

        """
        error_msg = ""
        for arg in args:
            if not isinstance(arg, Point):
                error_msg += f"object type: {type(arg)} is not Point type\n"
        if error_msg:
            raise TypeError(error_msg)
